name: Building and Pushing Images TO Docker Hub
on: 
    push:
        branches:
        - master
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout of the repository"
          uses: actions/checkout@v4

        - name: "Generate a random number"
          run: | 
            echo "version_number=$(echo $RANDOM)" >> $GITHUB_ENV
            echo $GITHUB_ENV

         
        - name: "Build the image"
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple_app_devops:1 .

        - name: "Login to Docker"
          run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: "Push to Docker Hub"
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_app_devops:1

        
