name: Building and Pushing Images TO Docker Hub
on: 
    push:
        branches:
        - master
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout of the repository"
          uses: actions/checkout@v4

        - name: "Generate a random number"
          run: | 

            VERSION_NUMBER=$( echo $RANDOM)


            day_data=$(echo "$(date)" | cut -d" " -f1)
            month_data=$(echo "$(date)" | cut -d" " -f3)
            time_data=$(echo "$(date)" | cut -d" " -f5)

            total_data="$VERSION_NUMBER"_"$day_data"_"$month_data"_"$time_data"


            time_data=$(echo "${time_data//\:/_}")


            total_data="$VERSION_NUMBER"_"$day_data"_"$month_data"_"$time_data"

            echo "VERSION_NUMBER=$total_data" >> $GITHUB_ENV
            
         
        - name: "Build the image"
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple_app_devops:${{ env.VERSION_NUMBER }} .

        - name: "Login to Docker"
          run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: "Push to Docker Hub"
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_app_devops:${{ env.VERSION_NUMBER }}

        
