name: "Deployment to EC2 Instance"
on: 
    workflow_run:
        workflows: ["Building and Pushing Images TO Docker Hub"]
        types: ["completed"]
        branches: 
        - master
jobs:
    deploy_app:
        runs-on: ubuntu-latest
        steps:
        - name: "Checkout the repository"
          uses: actions/checkout@v4
          
        - name: "Deploy to SSH"
          uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
          with:
            EC2_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            EC2_URL: ${{ secrets.AWS_IP }}
          env: 
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{ secrets.AWS_IP }}
            USERNAME: ${{ secrets.AWS_EC2_USER }}

        - name: "Update EC2"
          run: | 

            ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_IP }} "sudo apt-get update && sudo apt-get install docker -y"
             